# Site settings
title: Loblaw's Law Blog
header-img: img/home-bg.png
email: abhi+testlearn@flatironschool.com
copyright_name: abhi-testlearn
description: > # this means to ignore newlines until "baseurl:"
  My adventures on Learn
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  abhi-testlearn
learn_profile: abhi-testlearn
email_username: abhi+testlearn@flatironschool.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
